language: ruby
cache: bundler
rvm:
  - 2.6
  - &latest_ruby 2.6

before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.8"
